// <auto-generated />
using System;
using CITADT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CITADT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CITADT.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8661),
                            Description = "Tin tức mới nhất của Trung tâm",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Tin tức",
                            Slug = "tin-tuc"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8663),
                            Description = "Thông tin về các khóa đào tạo",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Đào tạo",
                            Slug = "dao-tao"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8665),
                            Description = "Hoạt động nghiên cứu khoa học",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Nghiên cứu khoa học",
                            Slug = "nghien-cuu-khoa-hoc"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8667),
                            Description = "Thông tin về chuyển đổi số",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Chuyển đổi số",
                            Slug = "chuyen-doi-so"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8668),
                            Description = "Các sự kiện của Trung tâm",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Sự kiện",
                            Slug = "su-kien"
                        });
                });

            modelBuilder.Entity("CITADT.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeaturedImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "<p>Ngày 01/06/2024, Trung tâm Ứng dụng Công nghệ thông tin và Chuyển đổi số đã tổ chức lễ khai giảng khóa đào tạo Công nghệ thông tin với nhiều chuyên đề hấp dẫn.</p><p>Các học viên sẽ được tiếp cận với những kiến thức và kỹ năng mới nhất trong lĩnh vực CNTT, giúp nâng cao năng lực cạnh tranh trong thời đại số.</p><p>Khóa học kéo dài 3 tháng với sự tham gia giảng dạy của các giảng viên có nhiều kinh nghiệm.</p>",
                            CreatedAt = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeaturedImage = "/img/news/khai-giang.jpg",
                            IsFeatured = true,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "khai-giang-khoa-dao-tao-cntt-thang-6-2024",
                            Summary = "Trung tâm Ứng dụng CNTT và Chuyển đổi số tổ chức khai giảng khóa đào tạo mới",
                            Title = "Khai giảng khóa đào tạo CNTT tháng 6/2024",
                            ViewCount = 152
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 4,
                            Content = "<p>Ngày 15/5/2024, Trường Đại học Hải Phòng phối hợp với Trung tâm Ứng dụng Công nghệ thông tin và Chuyển đổi số tổ chức hội thảo với chủ đề \"Chuyển đổi số trong giáo dục đại học\".</p><p>Hội thảo đã thu hút sự tham gia của nhiều chuyên gia hàng đầu trong lĩnh vực giáo dục và công nghệ thông tin. Các bài tham luận đã đề cập đến những thách thức và cơ hội trong quá trình chuyển đổi số tại các trường đại học Việt Nam.</p><p>Thông qua hội thảo, các đại biểu đã chia sẻ những kinh nghiệm quý báu và đề xuất các giải pháp thiết thực để thúc đẩy quá trình chuyển đổi số trong môi trường giáo dục đại học.</p>",
                            CreatedAt = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeaturedImage = "/img/news/hoi-thao.jpg",
                            IsFeatured = true,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "hoi-thao-ve-chuyen-doi-so-trong-giao-duc-dai-hoc",
                            Summary = "Trường Đại học Hải Phòng tổ chức hội thảo về chuyển đổi số trong giáo dục đại học",
                            Title = "Hội thảo về Chuyển đổi số trong giáo dục đại học",
                            ViewCount = 243
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CategoryId = 2,
                            Content = "<p>Trung tâm Ứng dụng Công nghệ thông tin và Chuyển đổi số thông báo lịch thi chứng chỉ Tin học ứng dụng A, B tháng 7/2024 như sau:</p><ul><li>Thời gian: 8h00 ngày 20/7/2024</li><li>Địa điểm: Phòng máy tính - Tầng 2 Nhà B3, Trường Đại học Hải Phòng</li><li>Hạn đăng ký: 15/7/2024</li></ul><p>Các học viên đăng ký tại Văn phòng Trung tâm, tầng 2 Nhà B3 hoặc qua email: citadt@dhhp.edu.vn</p>",
                            CreatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeaturedImage = "/img/news/chung-chi.jpg",
                            IsFeatured = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "lich-thi-chung-chi-tin-hoc-thang-7-2024",
                            Summary = "Thông báo lịch thi chứng chỉ Tin học ứng dụng A, B tháng 7/2024",
                            Title = "Lịch thi chứng chỉ Tin học tháng 7/2024",
                            ViewCount = 105
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CategoryId = 3,
                            Content = "<p>Trung tâm Ứng dụng Công nghệ thông tin và Chuyển đổi số vừa triển khai dự án ứng dụng trí tuệ nhân tạo (AI) trong quản lý đào tạo tại Trường Đại học Hải Phòng.</p><p>Dự án nhằm tự động hóa các quy trình quản lý đào tạo, hỗ trợ công tác ra quyết định và cải thiện trải nghiệm học tập của sinh viên. Hệ thống sẽ có khả năng phân tích dữ liệu lớn, đưa ra các dự báo về kết quả học tập và đề xuất các biện pháp cải thiện.</p><p>Giai đoạn đầu của dự án dự kiến sẽ hoàn thành vào cuối năm 2024 và sẽ được triển khai thử nghiệm tại một số khoa của trường.</p>",
                            CreatedAt = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeaturedImage = "/img/news/ai-project.jpg",
                            IsFeatured = true,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "gioi-thieu-du-an-ung-dung-ai-trong-quan-ly-dao-tao",
                            Summary = "Trung tâm triển khai dự án ứng dụng AI trong quản lý đào tạo",
                            Title = "Giới thiệu dự án ứng dụng AI trong quản lý đào tạo",
                            ViewCount = 178
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            CategoryId = 2,
                            Content = "<p>Trung tâm Ứng dụng Công nghệ thông tin và Chuyển đổi số thông báo tuyển sinh các khóa đào tạo CNTT tháng 8/2024 như sau:</p><ol><li>Khóa học Lập trình Web với ASP.NET Core MVC</li><li>Khóa học Phát triển ứng dụng di động với React Native</li><li>Khóa học Phân tích dữ liệu với Python</li><li>Khóa học IoT cơ bản</li></ol><p>Thời gian học: Tối thứ 3, 5, 7 hàng tuần</p><p>Địa điểm: Phòng học - Tầng 2 Nhà B3, Trường Đại học Hải Phòng</p><p>Liên hệ đăng ký: Văn phòng Trung tâm, tầng 2 Nhà B3 hoặc hotline: 0773.171.171</p>",
                            CreatedAt = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeaturedImage = "/img/news/tuyen-sinh.jpg",
                            IsFeatured = false,
                            IsPublished = true,
                            PublishedAt = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "thong-bao-tuyen-sinh-cac-khoa-dao-tao-cntt-thang-8-2024",
                            Summary = "Trung tâm thông báo tuyển sinh các khóa đào tạo CNTT tháng 8/2024",
                            Title = "Thông báo tuyển sinh các khóa đào tạo CNTT tháng 8/2024",
                            ViewCount = 82
                        });
                });

            modelBuilder.Entity("CITADT.Models.NewsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.HasIndex("TagId");

                    b.ToTable("NewsTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NewsId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            NewsId = 1,
                            TagId = 3
                        },
                        new
                        {
                            Id = 3,
                            NewsId = 1,
                            TagId = 4
                        },
                        new
                        {
                            Id = 4,
                            NewsId = 2,
                            TagId = 2
                        },
                        new
                        {
                            Id = 5,
                            NewsId = 2,
                            TagId = 5
                        },
                        new
                        {
                            Id = 6,
                            NewsId = 3,
                            TagId = 1
                        },
                        new
                        {
                            Id = 7,
                            NewsId = 3,
                            TagId = 4
                        },
                        new
                        {
                            Id = 8,
                            NewsId = 4,
                            TagId = 7
                        },
                        new
                        {
                            Id = 9,
                            NewsId = 4,
                            TagId = 5
                        },
                        new
                        {
                            Id = 10,
                            NewsId = 4,
                            TagId = 8
                        },
                        new
                        {
                            Id = 11,
                            NewsId = 5,
                            TagId = 1
                        },
                        new
                        {
                            Id = 12,
                            NewsId = 5,
                            TagId = 3
                        },
                        new
                        {
                            Id = 13,
                            NewsId = 5,
                            TagId = 6
                        });
                });

            modelBuilder.Entity("CITADT.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8750),
                            Name = "CNTT",
                            Slug = "cntt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8751),
                            Name = "Chuyển đổi số",
                            Slug = "chuyen-doi-so"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8753),
                            Name = "Đào tạo",
                            Slug = "dao-tao"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8754),
                            Name = "Chứng chỉ",
                            Slug = "chung-chi"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8755),
                            Name = "Công nghệ",
                            Slug = "cong-nghe"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8756),
                            Name = "IoT",
                            Slug = "iot"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8758),
                            Name = "AI",
                            Slug = "ai"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8759),
                            Name = "Big Data",
                            Slug = "big-data"
                        });
                });

            modelBuilder.Entity("CITADT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8525),
                            Email = "admin@citadt.dhhp.edu.vn",
                            FullName = "Administrator",
                            IsActive = true,
                            IsAdmin = true,
                            Password = "Admin@123",
                            PhoneNumber = "0773171171",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8528),
                            Email = "editor@citadt.dhhp.edu.vn",
                            FullName = "Biên Tập Viên",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "Editor@123",
                            PhoneNumber = "0912345678",
                            Username = "editor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 6, 16, 35, 6, 555, DateTimeKind.Local).AddTicks(8529),
                            Email = "giangvien@citadt.dhhp.edu.vn",
                            FullName = "Giảng Viên",
                            IsActive = true,
                            IsAdmin = false,
                            Password = "Giangvien@123",
                            PhoneNumber = "0987654321",
                            Username = "giangvien"
                        });
                });

            modelBuilder.Entity("CITADT.Models.News", b =>
                {
                    b.HasOne("CITADT.Models.User", "Author")
                        .WithMany("News")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CITADT.Models.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CITADT.Models.NewsTag", b =>
                {
                    b.HasOne("CITADT.Models.News", "News")
                        .WithMany("NewsTags")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CITADT.Models.Tag", "Tag")
                        .WithMany("NewsTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CITADT.Models.Category", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("CITADT.Models.News", b =>
                {
                    b.Navigation("NewsTags");
                });

            modelBuilder.Entity("CITADT.Models.Tag", b =>
                {
                    b.Navigation("NewsTags");
                });

            modelBuilder.Entity("CITADT.Models.User", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
